== devonfw Java Quality Profile

This plugin comes with a quality profile containing not only the previously described rules, but also rules from other plugins that are vital to ensure optimal code quality. You can download these plugins directly onto your SonarQube instance via its marketplace or install them manually. For more information on the installation of plugins, see https://docs.sonarqube.org/latest/setup/install-plugin/[here].
If you have this devon4j plugin installed, you should make sure to install the following plugins, so that the quality profile can be properly initialized at startup:

* https://github.com/checkstyle/sonar-checkstyle[Checkstyle]
* https://github.com/QualInsight/qualinsight-plugins-sonarqube-smell[Code Smells]
* https://github.com/spotbugs/sonar-findbugs[FindBugs]
* https://github.com/jensgerdes/sonar-pmd[PMD]

You can either associate this profile with certain projects or set it as default to make it active for every project. If you want to make changes to the profile, just create a copy of it. You will then be able to make your adjustments, like including or excluding rules, to that copy.

For further information on quality profiles and their setup, please follow the https://docs.sonarqube.org/latest/instance-administration/quality-profiles/[SonarQube documentation on Quality Profiles].
